### ISSUE TITLE
issue where player's can't interact with the server anymore but can still see chat and get hit.

### ISSUE THREAD

**Issue by RestartFU** [df-mc/dragonfly#433]
here is my POV:
https://www.youtube.com/watch?v=MA2JH9q5anc
and here is Tal's POV:
https://streamable.com/amax11

**Comment by T14Raptor** [comment]
Is there a way to reproduce this?

**Comment by Sandertv** [comment]
I have a hunch this might be a gophertunnel bug because I recall a similar issue a while back in Portal but it's difficult to debug this without way to reproduce this or a pprof goroutine profile.

**Comment by provsalt** [comment]
I have a similar issue where the player is frozen too but the player can still break blocks
https://www.youtube.com/watch?v=beR5qx2cMLE
(on the left is my pc and on the right is my phone)

**Comment by Sandertv** [comment]
With the latest commits this issue appears to be resolved(?) Please do feel free to let us know if it happens again.

**Comment by Sandertv** [comment]
Going to close this. Again, if it ever happens again, please let us know.

**Comment by JustTalDevelops** [comment]
This is happening again.

**Comment by Sandertv** [comment]
Closing this now as it seems this is now fixed. Please let us know if this does happen again.

**Comment by RestartFU** [comment]
> Closing this now as it seems this is now fixed. Please let us know if this does happen again.

this issue still happens when subchunk requests are disabled ![image-12.png](https://github.com/df-mc/dragonfly/assets/45609733/0f60b77b-e265-4040-9b46-b40a394a23b7)

**Comment by RestartFU** [comment]
should I get you a pprof profile?
