### ISSUE TITLE
Crafting recipes are incomplete

### ISSUE THREAD

**Issue by Flonja** [df-mc/dragonfly#864]
### What the user sees
(Even though the materials are there, the recipe doesn't give a diamond pickaxe)
![image](https://github.com/df-mc/dragonfly/assets/20887403/6a67bf29-50b0-4057-a3e6-74130f85c6ec)
(When in creative the items show up like they are supposed to do)
![image](https://github.com/df-mc/dragonfly/assets/20887403/75e3ac54-e3cf-4779-bd04-411ab86a4a8f)
## What debugging will do
In `server/item/recipe/vanilla.go`:
```patch
-	for _, s := range craftingRecipes.Shaped {
+	for i, s := range craftingRecipes.Shaped {
		input, ok := s.Input.Items()
		output, okTwo := s.Output.Stacks()
+		for _, out := range s.Output {
+			if out.Name == "minecraft:diamond_pickaxe" {
+				fmt.Printf("%v: ok1?%v ok2?%v\n", i, ok, okTwo) 
#				Returns: "208: ok1?false ok2?true"
+				if !ok {
+					_, _ = s.Input.Items()
#					Breakpoint here
+				}
+				if !okTwo {
+					_, _ = s.Output.Stacks()
#					Breakpoint here
+				}
+			}
+		}
		if !ok || !okTwo {
			// This can be expected to happen - refer to the comment above.
			continue
		}
		Register(Shaped{
			shape: Shape{int(s.Width), int(s.Height)},
			recipe: recipe{
```
Which led me to this:
![image](https://github.com/df-mc/dragonfly/assets/20887403/6a4398b7-c6ba-44ef-86e9-cd6dbea3bc3f)
Where it tried to recognize an empty item(?) I don't know how it is supposed to be generated, but it does seem to be the fault. 
It would make sense why the sword and shovel recipes were showing up, since they are shapeless recipes and these are shaped.

**Comment by TwistedAsylumMC** [comment]
Fixed in https://github.com/df-mc/dragonfly/commit/223f13677b87f1116e2084299689a3ea91288de9

**Comment by Flonja** [comment]
Problem still occurs

![image](https://github.com/df-mc/dragonfly/assets/20887403/34c4846c-7e20-44b1-91c8-571c620d8f15)

**Comment by DaPigGuy** [comment]
This appears to be fixed
